version: '3.8'

services:
  # Existing services (MongoDB handled by supervisor)
  
  # PostgreSQL for VC-specific data
  postgres:
    image: postgres:15
    container_name: verssai_postgres
    environment:
      POSTGRES_DB: verssai_vc
      POSTGRES_USER: verssai_user
      POSTGRES_PASSWORD: verssai_secure_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - verssai_network

  # n8n Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: verssai_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=verssai_admin
      - N8N_BASIC_AUTH_PASSWORD=verssai_n8n_2024
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - EXECUTIONS_PROCESS=main
      - EXECUTIONS_MODE=regular
      - N8N_LOG_LEVEL=info
      # Database connection for n8n workflows
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=verssai_vc
      - DB_POSTGRESDB_USER=verssai_user
      - DB_POSTGRESDB_PASSWORD=verssai_secure_password_2024
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows:ro
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - verssai_network

  # ChromaDB for Vector Storage (Level 3 RAG)
  chromadb:
    image: chromadb/chroma:latest
    container_name: verssai_chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped
    networks:
      - verssai_network

volumes:
  postgres_data:
    driver: local
  n8n_data:
    driver: local
  chromadb_data:
    driver: local

networks:
  verssai_network:
    driver: bridge