// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chwjydignjdyhkpgkdsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNod2p5ZGlnbmpkeWhrcGdrZHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1MTk0MjksImV4cCI6MjA1NTA5NTQyOX0.URxy4p5ApRmSUFlwBZdPvQYTgkyoVqMpGAg6Z-AyeGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);